### ISSUE TITLE
when supplying centerPoint array in different order, centerPoint coordinates are switched (Leaflet)

### ISSUE THREAD

**Issue by brausepulver** [LarsWiegers/laravel-maps#13]
When supplying a centerPoint array ordered `['long' => ..., 'lat' => ...]` rather than `['lat' => ..., 'long' => ...]`, the coordinates are switched. This is because of

https://github.com/LarsWiegers/laravel-maps/blob/cd464645e89695871a5a4a06c7213280cb78d519/resources/views/components/leaflet.blade.php#L26

I suggest changing it to
`var mymap = L.map('{{$mapId}}').setView([{{$centerPoint['lat'] ?? $centerPoint[0]}}, {{$centerPoint['long'] ?? $centerPoint[1]}}], {{$zoomLevel}});`

**Comment by LarsWiegers** [comment]
Its been 2 weeks, merging the pr.
