### ISSUE TITLE
You cannot edit the marker's coordinates by clicking on it.

### ISSUE THREAD

**Issue by masterawss** [LarsWiegers/laravel-maps#15]
You cannot edit the marker's coordinates by clicking on it.

**Comment by LarsWiegers** [comment]
Hi, 
Thx for creating an issue. What are you having trouble with? 

If you can please include a test repository

**Comment by LarsWiegers** [comment]
Hi @masterawss, please let me know or else i have to close the issue.

cant help with an issue i dont understand haha.
