### ISSUE TITLE
[Google Map] Marker not shown

### ISSUE THREAD

**Issue by mohamedsabil83** [LarsWiegers/laravel-maps#18]
The map itself is shown and zooming works but the marker/markers are not shown.

I'm using the latest version of the package with Laravel 8 and PHP 8

**Comment by LarsWiegers** [comment]
Hey mohammed, 

Thx for the issue. im going to look into it!

**Comment by LarsWiegers** [comment]
Hey Mohammed, 

I found the bug and fixed it. A new release has been published. Give packagist a few minutes to update and you should be able to download it then. Can you let me know if it works for you?

**Comment by mohamedsabil83** [comment]
It works now. Thanks, @LarsWiegers
