### ISSUE TITLE
Compatibility with Laravel 9

### ISSUE THREAD

**Issue by fgaroby** [LarsWiegers/laravel-maps#21]
Hi,
Currently, I can't upgrade my personal project from Laravel 8 to 9, because of the `laravel-maps` package, and one of its dependencies : `illuminate/support`.
By upgrading this dependancy from 8.0 to 9.0, it will allow to upgrade to Laravel 9.

**Comment by LarsWiegers** [comment]
Hey! Thanks for creating the issue. pls see my comment on your pr.
