### ISSUE TITLE
Migrating from gonoware/laravel-maps / Javascript events available?

### ISSUE THREAD

**Issue by RoelReijn** [LarsWiegers/laravel-maps#23]
Hey Lars,

Thanks for trying to update `gonoware/laravel-maps` to PHP8 and for creating this repository. I'm currently trying to update one of my Laravel instances from version 8 to 9 and was forced away from `gonoware/laravel-maps` since there hasn't been any activity from the owner for over a year.

After a bit of puzzling, I found that `$markers[lng]` in this repository has been changed to `$markers[long]`. However, I still haven't figured out if it is possible to hook into the Leaflet Map via Javascript events as it was possible in `gonoware/laravel-maps`. See [this](https://gitlab.com/gonoware/laravel-maps/-/tree/master#events) section of the readme for a reference.

Is this something I have to look for in Leaflet.JS or does your code have possibilities for this as well? Thanks in advance!

PS. Would you like me to create a Pull request for a little documentation for the migration from gonoware/laravel-maps to your repository? Or don't you think that's necessary?

**Comment by LarsWiegers** [comment]
Hey Roel!

Thanks for creating the issue. Like seeing young developers using my open source stuff. 
I had forgotten about the gonoware/laravel-maps package, thx for bringing it up again.

We currently dont support hooking into the leaflet or google maps js instance. 
it might be available on the page if you can get the variable mymap somewhere.
But that would be outside of the the currently supported use cases.
Is that something you need?

A pr with a guide would be great! What would you need from me for that?

**Comment by LarsWiegers** [comment]
Hey @RoelReijn is this something you still want to continue working on? 

Please let me know

**Comment by LarsWiegers** [comment]
@RoelReijn In about a week im going to close the issue as it has gone stale. if you still want this please tell me.
