### ISSUE TITLE
Multiple Maps Causing Errors

### ISSUE THREAD

**Issue by ryangurn** [LarsWiegers/laravel-maps#28]
I am attempting to use multiple maps for different purposes on the same page.

This appears to be causing issues with the `let map= ...`

The error is as follows: `SyntaxError: Can't create duplicate variable: 'url'`

Any recommendations on how to address this? The url should only need to be declared a single time per page.

Is there a way to prevent it from attempting to create a duplicate variable.

**Comment by LarsWiegers** [comment]
Hi @ryangurn, 

in the the pr is the code to fix this issue. I will be making a release shortly

**Comment by ryangurn** [comment]
Great thanks!
