### ISSUE TITLE
Multiple markers dynamically

### ISSUE THREAD

**Issue by rjcalifornia** [LarsWiegers/laravel-maps#32]
I know blade tags dont have to use the {{ and }} to pass data

https://github.com/LarsWiegers/laravel-maps/issues/6

Currently, there's no way to add markers dynamically. For instance, I query the DB and get an array of coordinates. Currently you cannot loop through each location to place a marker on a single map (not multiple maps). 

May be there's a way but I can't find it.

**Comment by LarsWiegers** [comment]
can you give some example code of what you are trying to do?

**Comment by rjcalifornia** [comment]
Sorry for the late reply. If I wanted to make place multiple markes on the SAME map, it won't work:
```

<x-maps-leaflet :markers="[
@foreach ($locations as $location)
['lat' => $location->latitude, 'long' => $location->longitude',
@endforeach
]"></x-maps-leaflet>
```

**Comment by LarsWiegers** [comment]
So it is probably a good idea to this loop in your controller that way you can pass a single array to the component.

**Comment by rjcalifornia** [comment]
> So it is probably a good idea to do this loop in your controller that way you can pass a single array to the component.

Well, yeah. I actually did that after the first code I posted didn't work. I didn't work, the map was blank for some reason.

**Comment by LarsWiegers** [comment]
Without more code / errors in the console you are getting its going to be hard for me to diagnose the problem

**Comment by rjcalifornia** [comment]
Alright...

**Comment by matb987** [comment]
can you give me an example of how you would make this loop as i keep getting the error: Undefined array key 0
