### ISSUE TITLE
Error endif when put HTML in popup info ?

### ISSUE THREAD

**Issue by t-prod** [LarsWiegers/laravel-maps#38]
Hi,

Thanks for your awesome package. I try to display an info popup with some HTML.
When I do this : 

`<x-maps-google :zoomLevel="5" :centerPoint="['lat' => 43, 'long' => 5]" :markers="[['lat' => 43.5517, 'long' => 5.19472, 'title' => 'Your Title', 'info' => '<b>Title</b><br>Address<br>Zipcode City<br><a href="https://www.google.fr/maps/search/?api=1&query=Avenues+">Route</a>']]"></x-maps-google>`

And I have this error :

![image](https://user-images.githubusercontent.com/1824638/212886536-78d7c884-5004-4ad1-90cb-f38625531167.png)

How can I handle the HTML content in this variable ? Should I convert to something ?

Regards

**Comment by LarsWiegers** [comment]
Hey! so the problem is that the qoutes are not escaped,
this works: 
```
'info' => '<b>Title</b><br>Address<br>Zipcode City<br><a href=\'https://www.google.fr/maps/search/?api=1&query=Avenues+\'>Route</a>']
```

**Comment by t-prod** [comment]
That's perfect I think I can go with a stripslashes too ;)
Thanks again

**Comment by LarsWiegers** [comment]
awesome!
