### ISSUE TITLE
clear up section about html escaping

### ISSUE THREAD

**Issue by LarsWiegers** [LarsWiegers/laravel-maps#39]
Make the section of the documentation ( readme for now) clearer on how HTML is not escaped and as such quotes will interfere with the resulting code. the double quotes character should not be used.

**Comment by anushkabishnoi** [comment]
Hello, this is my first experience with open source contributions. Would really appreciate it if you explained exactly what is needed to be done.

I would love to work on this issue.

Thanks in advance! :)

**Comment by LarsWiegers** [comment]
Hey! Awesome that you want to start with open source. This repository was my first way into open source to 😄 

What needs to happen:
Add a section to this part of the readme
https://github.com/LarsWiegers/laravel-maps#usage
which explains that double qoutes are not allowed ( if not escaped ) in the info box of the markers

**Comment by LarsWiegers** [comment]
fixes by #42
