### ISSUE TITLE
update leaflet

### ISSUE THREAD

**Issue by DifficultPhil** [LarsWiegers/laravel-maps#45]
current version of leaflet is - 1.9.4 on https://www.npmjs.com/package/leaflet
u can update this? or update version only on blade template is worked?

**Comment by LarsWiegers** [comment]
I will look at this next week. Thanks for the issue 😀

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ilya Filimonov ***@***.***>
Sent: Friday, May 26, 2023 5:02:04 PM
To: LarsWiegers/laravel-maps ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LarsWiegers/laravel-maps] update leaflet (Issue #45)


current version of leaflet is - 1.9.4 on https://www.npmjs.com/package/leaflet
u can update this? or update version only on blade template is worked?
