### ISSUE TITLE
Unable to locate a class or view for component [maps-leaflet].

### ISSUE THREAD

**Issue by febriaricandra** [LarsWiegers/laravel-maps#49]
![gambar](https://github.com/LarsWiegers/laravel-maps/assets/52602319/fcc53830-5782-41ef-9c66-993739cffda7)
Hi, i found issue when i push to production. it seems the component locate unknown. can you fix this issue?

**Comment by LarsWiegers** [comment]
Hey @febriaricandra what version are you using, i cant seem to reproduce it. Can you also send me your composer.json file?

**Comment by LarsWiegers** [comment]
Closing as I did not get a respond. If you are experiencing this, pls feel free to reopen.
