### ISSUE TITLE
help with Leaflet.awesome-markers

### ISSUE THREAD

**Issue by NXC-Controls** [LarsWiegers/laravel-maps#54]
im tyring to use https://github.com/lennardv2/Leaflet.awesome-markers 
tried to pass icon as suggested but getting error 

$markers[] = [
    'lat' => $record->latitude,
    'long' => $record->longitude,
    'info' => $info, 
    'icon' => L.AwesomeMarkers.icon(array( 
        'icon' => 'spinner', 
        'prefix' => 'fa',  
        'markerColor' => 'red' 
    ))
  ];

and 

<x-maps-leaflet id="map" style="height: 400px;" tile-host="mapbox" :zoomLevel="11" :centerPoint="['lat' => 23.0225, 'long' => 72.5714]"
          :markers="$markers"></x-maps-leaflet>

**Comment by tarikbouchaala** [comment]
> im tyring to use https://github.com/lennardv2/Leaflet.awesome-markers tried to pass icon as suggested but getting error
> 
> $markers[] = [ 'lat' => $record->latitude, 'long' => $record->longitude, 'info' => $info, 'icon' => L.AwesomeMarkers.icon(array( 'icon' => 'spinner', 'prefix' => 'fa', 'markerColor' => 'red' )) ];
> 
> and
> 
> <x-maps-leaflet id="map" style="height: 400px;" tile-host="mapbox" :zoomLevel="11" :centerPoint="['lat' => 23.0225, 'long' => 72.5714]"           :markers="$markers">

I don't know how to use the library in the laravel maps but for me when I wanted a marker to look different I just change the icon property like this :
 <x-maps-leaflet :centerPoint="['lat' => 35.693067, 'long' => -5.330376]" :zoomLevel="15" :fitToBounds="true" :markers="[
        ['lat' => 35.693067, 'long' => -5.330376, 'icon' => asset('marker.png')],
        ['lat' => 35.693387, 'long' => -5.331271],
        ['lat' => 35.694045, 'long' => -5.329147],
        ['lat' => 35.693051, 'long' => -5.328358],
        ['lat' => 35.693025, 'long' => -5.329705],
    ]"></x-maps-leaflet>
    The marker.png is an icon

**Comment by LarsWiegers** [comment]
Hey @NXC-Controls and @tarikbouchaala this library does not support working with https://github.com/lennardv2/Leaflet.awesome-markers. We only support what is said in the readme.

**Comment by tarikbouchaala** [comment]
> Hey @NXC-Controls and @tarikbouchaala this library does not support working with https://github.com/lennardv2/Leaflet.awesome-markers. We only support what is said in the readme.

Yeah yeah I gave him an alternative
