### ISSUE TITLE
Blade Tags

### ISSUE THREAD

**Issue by CrisCrassus** [LarsWiegers/laravel-maps#6]
If I try to use blade tags to pull a latitude/longtitude from a DB it doesn't seem to like it.  I've checked my syntax and as far as I'm aware it's ok.

<x-maps-leaflet :centerPoint="['lat' => {{$hotel->latitude}}, 'long' => {{$hotel->latitude}}]" :markers="[['lat' => {{$hotel->latitude}}, 'long' => {{$hotel->latitude}}]]"  :zoomLevel="15"></x-maps-leaflet>

**Comment by CrisCrassus** [comment]
`<x-maps-leaflet :centerPoint="['lat' => {{$hotel->latitude}}, 'long' => {{$hotel->latitude}}]" :markers="[['lat' => {{$hotel->latitude}}, 'long' => {{$hotel->latitude}}]]"  :zoomLevel="15"></x-maps-leaflet>` This is my code

**Comment by LarsWiegers** [comment]
Hi!, 
Thanks for creating an issue. FYI i believe in the blade tags you dont have to use the {{ and }} to pass data. See this docs sample:
https://laravel.com/docs/8.x/blade#passing-data-to-components.

Please let me know if it works by removing them :).

**Comment by CrisCrassus** [comment]
Works now :) thanks
