### ISSUE TITLE
Tiles

### ISSUE THREAD

**Issue by CrisCrassus** [LarsWiegers/laravel-maps#9]
Hi!
What do I need to declare in the view to change the tile host?
`<x-maps-leaflet
                                            :tileHost="'http://c.tile.stamen.com/toner-labels/{z}/{x}/{y}.png'"
                                            :centerPoint="['lat' => $hotel->latitude-0.8, 'long' => $hotel->longitude]"
                                            :zoomLevel="9"
                                            :markers="[['lat' => $hotel->latitude, 'long' => $hotel->longitude]]">`
This is what I'm doing at the moment, but all I get is a grey box.

Thanks!

**Comment by LarsWiegers** [comment]
Hi! I have some time later this week. then I will take a look at it.

**Comment by LarsWiegers** [comment]
Hi!

So i got you example working. But it seems that your tilehost only displays name of continents? Is that correct?
To get the example working I added an else statement to the tilehost definitions. This should be in the new release im going to write after this. Can you let me know if it works for you with this new release?

**Comment by LarsWiegers** [comment]
@CrisCrassus 
The new version has been released. 
https://github.com/LarsWiegers/laravel-maps/releases/tag/V0.4

it should also be on packagist by now. Please let me know if it works for you :)

**Comment by CrisCrassus** [comment]
Thanks, I will test soon but I will close the issue for now.
